Repository openshift-eng/jira-lifecycle-plugin, pull requests merged in 2024-07, with the labels that each got.

#95 server: handle `nil` target version during backport
  cmd/jira-lifecycle-plugin/server.go
  cmd/jira-lifecycle-plugin/server_test.go
Labels: approved, lgtm

#96 server: fix `nil` dependent version during backport
  cmd/jira-lifecycle-plugin/server.go
  cmd/jira-lifecycle-plugin/server_test.go
Labels: approved, lgtm

#98 server: don't backport to parent branch
  cmd/jira-lifecycle-plugin/server.go
  cmd/jira-lifecycle-plugin/server_test.go
Labels: approved, lgtm

#94 OCPBUGS-36651: Makefile: test commit
  Makefile
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#102 Remove openshift/ci-tools dependency
  cmd/jira-lifecycle-plugin/config.go
  cmd/jira-lifecycle-plugin/main.go
  go.mod
  go.sum
  vendor/github.com/openshift/ci-tools/LICENSE
  vendor/github.com/openshift/ci-tools/pkg/util/gzip/gzip.go
  vendor/modules.txt
Labels: ok-to-test, approved, lgtm

#103 server: improve comment for backport
  cmd/jira-lifecycle-plugin/server.go
  cmd/jira-lifecycle-plugin/server_test.go
Labels: approved, lgtm

#104 server: fix assignee race condition
  cmd/jira-lifecycle-plugin/server.go
  cmd/jira-lifecycle-plugin/server_test.go
Labels: approved, lgtm

#107 server.go: fix backport missing dependencies check
  cmd/jira-lifecycle-plugin/server.go
  cmd/jira-lifecycle-plugin/server_test.go
Labels: approved, lgtm

#108 server: fix backport bug caused by z-stream versions
  cmd/jira-lifecycle-plugin/server.go
  cmd/jira-lifecycle-plugin/server_test.go
Labels: approved, lgtm

#105 OCPBUGS-36840: Makefile: test commit 2
  Makefile
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
